CREATE SCHEMA IF NOT EXISTS recipes;

CREATE TABLE IF NOT EXISTS recipes.recipe_access_type (
                                        recipe_access_type     varchar(7)   primary key,
                                        name_ukr               varchar(50)  not null,
                                        name_eng               varchar(50)  not null
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_recipe_access_type on recipes.recipe_access_type(recipe_access_type);

CREATE TABLE IF NOT EXISTS recipes.recipe (
                              recipe_id            uuid         primary key,
                              title                varchar(100) not null,
                              note                 text         not null,
                              recipe_owner         uuid         not null,
                              recipe_access_type   varchar(7)   not null,
                              created_date         timestamp,
                              updated_date         timestamp,
                              constraint fk_recipe_users foreign key(recipe_owner) references access.users(user_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_recipe_recipe_id        on recipes.recipe(recipe_id);
CREATE INDEX IF NOT EXISTS ix_recipe_user_id        on recipes.recipe(recipe_owner);

CREATE TABLE IF NOT EXISTS recipes.tag (
                           tag_id               uuid             primary key,
                           title                varchar(100)     not null,
                           created_date         timestamp,
                           updated_date         timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_tag_tag_id        on recipes.tag(tag_id);

CREATE TABLE IF NOT EXISTS recipes.recipe_tag (
                                recipe_tag_id        bigint generated by default as identity(start with 1) primary key,
                                recipe_id            uuid   not null,
                                tag_id               uuid   not null,
                                created_date         timestamp,
                                updated_date         timestamp,
                                constraint fk_recipe_tag_recipe foreign key(recipe_id) references recipes.recipe(recipe_id),
                                constraint fk_recipe_tag_tag foreign key(tag_id) references recipes.tag(tag_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_recipe_tag_recipe_tag_id        on recipes.recipe_tag(recipe_tag_id);
CREATE INDEX IF NOT EXISTS ix_recipe_tag_recipe_id            on recipes.recipe_tag(recipe_id);
CREATE INDEX IF NOT EXISTS ix_recipe_tag_tag_id             on recipes.recipe_tag(tag_id);
CREATE INDEX IF NOT EXISTS ix_recipe_tag_recipe_id_u          on recipes.recipe_tag(recipe_id, tag_id);
